### ISSUE TITLE
Image logging error in depth head

### ISSUE THREAD

**Issue by melisandeteng** [cc-ai/omnigan#101]
In this [PR](https://github.com/cc-ai/omnigan/pull/97)
There are some issues in logging depth images from the real world (image is repeated) and then there's also a slight issue with colors in the mask images that are logged in comet.
(see this [experiment](https://www.comet.ml/melisandeteng/omnigan/c362c015697e4eeab65258ac61cd4b88?experiment-tab=images) )

**Comment by vict0rsch** [comment]
@melisandeteng I won't have time today but I'd be happy to peer-program with you tomorrow!

**Comment by alexrey88** [comment]
The weird coloring error for the masker logging has been found. The repeated image is due to the file val_r_resized_d.json, where each path for the depth task is the same ("d": "/network/tmp1/ccai/data/munit_dataset/testA_megadepth_resized/04.npy"). Working on finding why depth images are only logged once.

**Comment by melisandeteng** [comment]
Wow, thanks for spotting that @alexrey88 . It was a bit of a stupid error, but on the other hand, I'm glad it's not something more important !

**Comment by alexrey88** [comment]
My pleasure !! The trainer is running right now on my side and depth seems to be logged more than one time, see this [experiment](https://www.comet.ml/alexrey88/omnigan/eb270fdcdc544db4920f1e4f06a6cb2f?experiment-tab=images&groupBy=false&orderBy=desc&sortBy=step).

**Comment by melisandeteng** [comment]
I can't see the experiment, but I'm glad it looks promising ! 
What was the issue with depth being logged only once ?

**Comment by alexrey88** [comment]
Oh I think you will be able to see it now, my experiments were set to private. Actually I don't know what the issue was, I just let it run for a first look and it was being logged!

**Comment by melisandeteng** [comment]
Predictions after one epochs are just nan tensors for both masker and depth head ...

**Comment by melisandeteng** [comment]
There was a mistake in the simulated data depth map decoder. Input was thought as having values between 0 and 1, but they were already pixel values between 0-255.
The problem has been fixed
