### ISSUE TITLE
Some images have weird colors

### ISSUE THREAD

**Issue by 51N84D** [cc-ai/omnigan#104]
When doing inference, occasionally the generated image has a weird color scheme (maybe the channels are shuffled). 

Example:
![AB_410](https://user-images.githubusercontent.com/24759124/87348599-05335980-c523-11ea-98d9-1fbf32231b04.png)

**Comment by melisandeteng** [comment]
@51N84D  This was fixed with normalization right? So we can close the issue

**Comment by melisandeteng** [comment]
This was fixed in https://github.com/cc-ai/omnigan/pull/113
