### ISSUE TITLE
Change defaults hyperparameters

### ISSUE THREAD

**Issue by melisandeteng** [cc-ai/omnigan#126]
@tianyu-z Could you change in defaults whatever hyperparameters are best according to your empirical study please ? Thanks !

**Comment by tianyu-z** [comment]
The hyper-params that I found perform well in the Masker task but not other tasks. That's why I didn't update the defaults.yaml.

**Comment by vict0rsch** [comment]
still, it's our current best so let's make it default at least for the masker and we can change it later as we learn :)

**Comment by melisandeteng** [comment]
> still, it's our current best so let's make it default at least for the masker and we can change it later as we learn :)

@tianyu-z Can you make a quick PR for this? Thanks

**Comment by tianyu-z** [comment]
@melisandeteng Please check https://github.com/cc-ai/omnigan/pull/124
