### ISSUE TITLE
Different depth scaling approaches for smog

### ISSUE THREAD

**Issue by sashavor** [cc-ai/omnigan#131]
Compare log, linear, exponential training 
+ do a blind test on the same images

**Comment by vict0rsch** [comment]
@melisandeteng @alexrey88 can you link the presentation and conclusions here and then close? thanks!

**Comment by alexrey88** [comment]
Here's the [Google doc](https://docs.google.com/presentation/d/1QbAm0sToetdH2clnKTTQXfpAJQAeExEEbVIC2kafxw4/edit#slide=id.g96b425d20e_0_105)

@vict0rsch @tianyu-z @sashavor @51N84D If you could just give your opinion on the last slides we added recently, would be great (from slide 22 till the end)! :)

**Comment by sashavor** [comment]
The presentation is here: https://docs.google.com/presentation/d/1QbAm0sToetdH2clnKTTQXfpAJQAeExEEbVIC2kafxw4/

(Just in case people lost it)

**Comment by alexrey88** [comment]
Created a Google doc to summarize the results: [here](https://docs.google.com/document/d/12SNddg8eLUOGK_VrCbBjcUGwbKO-daxAsM40Eib7-Gs/edit?usp=sharing). We could discuss them at the next meeting!
