### ISSUE TITLE
Self-supervised surrogate tasks

### ISSUE THREAD

**Issue by vict0rsch** [cc-ai/omnigan#33]
Self-Supervised Learning of Pretext-Invariant Representations PIRL

https://arxiv.org/abs/1912.01991

**Comment by vict0rsch** [comment]
Data-Efficient Image Recognition with Contrastive Predictive Coding
https://arxiv.org/abs/1905.09272

**Comment by vict0rsch** [comment]
More papers here:

https://docs.google.com/document/d/1MD9vOTvPydYuSks-xJt7Cf64ijuOcr7i2_lOmj1Jk48/edit#heading=h.w3qa5fc9vrfa

**Comment by vict0rsch** [comment]
@alexrey88 if you have time, the self-supervision section will be of interest for our upcoming work

**Comment by alexrey88** [comment]
@vict0rsch cool i'll look into that :)
