### ISSUE TITLE
Pathlib error in tests

### ISSUE THREAD

**Issue by 51N84D** [cc-ai/omnigan#39]
For some reason I'm getting the error `ModuleNotFoundError: No module named 'omnigan'` when running `run.py` as is.

Changing `sys.path.append(str(Path(__file__).parent.parent.resolve()))` to `sys.path.append(str(Path(__file__).resolve().parent.parent))` in all the test programs fixes the problem for me. Is this the case for you guys?

**Comment by vict0rsch** [comment]
I think both should be fine as it depends on where you run the python interpreter from, either from root or within tests/

**Comment by tianyu-z** [comment]
Completely agreed with Sun:
If a script is located in /A/B/name.py

Path(__file__).parent.parent.resolve()
>>> /A/B
Path(__file__).resolve().parent.parent
>>>/A

In our situation, we should choose the latter one because the omnigan folder is here.

**Comment by vict0rsch** [comment]
there was a typo in the config locations which I just fixed but `python tests/run.py` runs fine ; if you'd rather run tests from *within* tests/ that's fine too, but don't remove the ability to run from root :)

**Comment by 51N84D** [comment]
Ah got it
