### ISSUE TITLE
TODO setup a get_losses func to assign the right loss according to the yaml

### ISSUE THREAD

**Issue by vict0rsch** [cc-ai/omnigan#63]
`def set_losses(self):` doesn't really ned to be a trainer method, it could be a pure function in `tutils` that takes `opts` and returns a `losses` `dict` which we would set to be a trainer attribute somewhere in its `__init__()`

**Comment by alexrey88** [comment]
I could do this, if that's ok with you. :) But why tutils and not utils tho, it's not tensor-related, is it?

**Comment by vict0rsch** [comment]
great! :) 

I mean it's not tensors but it's `pytorch`. It's a moving target right, it doesn't matter so much, worst case scenario we'll just move it around :p

**Comment by alexrey88** [comment]
true true!
